brew "fish"
brew "tmux"
brew "vim"
brew "stow"
brew "pinentry-mac"
brew "paperkey"
brew "ykman"
brew "tree"
brew "yarn", args: ["ignore-dependencies"]
brew "watchman"
brew "pyenv"
brew "adr-tools"
brew "gh"
brew "coreutils"
brew "pnpm"
tap "hashicorp/tap"
brew "terraform"
cask_args appdir: "/Applications"
cask "gpg-suite"
cask "ghostty"
cask "docker"
cask "visual-studio-code"
cask "windsurf"
cask "dbeaver-community"
cask"ngrok"