brew "stow"
brew "pinentry-mac"
brew "paperkey"
brew "ykman"
cask_args appdir: "/Applications"
tap "homebrew/cask"
cask "iterm2"
brew "autojump"
brew "tmux"
brew "tree"
brew "ack"
brew "vim"
brew "cmake"
cask "docker"
brew "zsh"
brew "yarn", args: ["ignore-dependencies"]
